import AppKit
import Foundation
import MateBridgeCore

public struct SystemPasteboard: PasteboardAccess {
    public init() {}

    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    public var changeCount: Int { NSPasteboard.general.changeCount }
    public var string: String? { NSPasteboard.general.string(forType: .string) }
    public var isConcealed: Bool {
        let types = NSPasteboard.general.types ?? []
        return Self.concealedTypes.contains { types.contains($0) }
    }

    public func write(_ text: String) -> Int {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        return pb.changeCount
    }
}

/// Clipboard sharing for the active session (T-054, docs/PROTOCOL.md 0x06). Polls the pasteboard every 0.5 s on its
/// own queue (`ClipboardEngine`); incoming text goes through a latest-value slot (at most one pending write, drained
/// by one task on the queue). Contents are never logged, only direction and byte count.
public final class ClipboardBridge: @unchecked Sendable {
    public static let defaultsKey = "clipboardSharingEnabled"
    public static let pollInterval: DispatchTimeInterval = .milliseconds(500)

    private let queue = DispatchQueue(label: "dev.matebridge.clipboard")
    private let logger = SessionLogger(component: "clipboard")
    private let sendLock = NSLock()
    private var _send: @Sendable (_ sessionID: UInt32, Message) -> Void = { _, _ in }
    private var engine: ClipboardEngine
    /// The newest CLIPBOARD waiting for the queue (one constant epoch: a session boundary clears it).
    private let incomingLock = NSLock()
    private var incoming = EpochCoalescer<Clipboard>()
    private var sessionID: UInt32?
    private var timer: DispatchSourceTimer?

    public init(pasteboard: PasteboardAccess = SystemPasteboard(), enabled: Bool) {
        self.engine = ClipboardEngine(pasteboard: pasteboard, enabled: enabled)
    }

    /// Where outgoing messages go (`SessionServer.sendToSession`); set once the server exists.
    public var send: @Sendable (_ sessionID: UInt32, Message) -> Void {
        get { sendLock.withLock { _send } }
        set { sendLock.withLock { _send = newValue } }
    }

    public func setEnabled(_ on: Bool) {
        queue.async { [self] in engine.setEnabled(on) }
    }

    /// The session became active: the current pasteboard is the baseline and is not sent.
    public func sessionStarted(sessionID: UInt32) {
        queue.async { [self] in
            self.sessionID = sessionID
            incomingLock.withLock { incoming.clear() }
            engine.begin()
            timer?.cancel()
            let t = DispatchSource.makeTimerSource(queue: queue)
            t.schedule(deadline: .now() + Self.pollInterval, repeating: Self.pollInterval)
            t.setEventHandler { [weak self] in self?.poll() }
            t.resume()
            timer = t
        }
    }

    public func sessionEnded() {
        queue.async { [self] in
            timer?.cancel()
            timer = nil
            sessionID = nil
            incomingLock.withLock { incoming.clear() }
            engine.end()
        }
    }

    /// A message from the active session; anything but CLIPBOARD is ignored. A newer message replaces a pending one.
    public func deliver(_ message: Message) {
        guard case .clipboard(let clip) = message else { return }
        if incomingLock.withLock({ incoming.offer(clip, epoch: 0) }) {
            queue.async { [self] in drainIncoming() }
        }
    }

    private func drainIncoming() {
        while let clip = incomingLock.withLock({ incoming.take(epoch: 0) }) {
            guard sessionID != nil, let bytes = engine.applyIncoming(clip) else { continue }
            logger.log(.info, "clipboard", sessionID: sessionID ?? 0, generation: 0, fields: "dir=in bytes=\(bytes)")
        }
    }

    private func poll() {
        guard let sessionID else { return }
        switch engine.poll() {
        case .nothing: break
        case .send(let clip):
            // Outgoing is bounded by construction: one poll per 0.5 s, at most one message each.
            send(sessionID, .clipboard(clip))
            logger.log(.info, "clipboard", sessionID: sessionID, generation: 0, fields: "dir=out bytes=\(clip.data.count)")
        case .tooLarge(let bytes):
            logger.log(.info, "clipboard_too_large", sessionID: sessionID, generation: 0, fields: "bytes=\(bytes)")
        }
    }
}
