import AppKit
import Foundation
import MateBridgeCore

/// What the bridge needs from the pasteboard; `NSPasteboard.general` in the app, a fake in tests.
public protocol PasteboardAccess: Sendable {
    var changeCount: Int { get }
    var string: String? { get }
    /// True when the current content is marked concealed, transient or auto-generated (password managers).
    var isConcealed: Bool { get }
    /// Replaces the contents with `text` and returns the new `changeCount`.
    func write(_ text: String) -> Int
}

public struct SystemPasteboard: PasteboardAccess {
    public init() {}

    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    public var changeCount: Int { NSPasteboard.general.changeCount }
    public var string: String? { NSPasteboard.general.string(forType: .string) }
    public var isConcealed: Bool {
        let types = NSPasteboard.general.types ?? []
        return Self.concealedTypes.contains { types.contains($0) }
    }

    public func write(_ text: String) -> Int {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        return pb.changeCount
    }
}

/// Clipboard sharing for the active session (T-054, docs/PROTOCOL.md 0x06). Polls the pasteboard every 0.5 s on its
/// own queue and feeds `ClipboardSync`; incoming text is written to the pasteboard. Contents are never logged, only
/// direction and byte count.
public final class ClipboardBridge: @unchecked Sendable {
    public static let defaultsKey = "clipboardSharingEnabled"
    public static let pollInterval: DispatchTimeInterval = .milliseconds(500)

    private let queue = DispatchQueue(label: "dev.matebridge.clipboard")
    private let pasteboard: PasteboardAccess
    private let logger = SessionLogger(component: "clipboard")
    private let sendLock = NSLock()
    private var _send: @Sendable (_ sessionID: UInt32, Message) -> Void = { _, _ in }
    private var sync: ClipboardSync
    private var sessionID: UInt32?
    private var timer: DispatchSourceTimer?

    public init(pasteboard: PasteboardAccess = SystemPasteboard(), enabled: Bool) {
        self.pasteboard = pasteboard
        self.sync = ClipboardSync(enabled: enabled)
    }

    /// Where outgoing messages go (`SessionServer.sendToSession`); set once the server exists.
    public var send: @Sendable (_ sessionID: UInt32, Message) -> Void {
        get { sendLock.withLock { _send } }
        set { sendLock.withLock { _send = newValue } }
    }

    public func setEnabled(_ on: Bool) {
        queue.async { [self] in sync.setEnabled(on, changeCount: pasteboard.changeCount) }
    }

    /// The session became active: the current pasteboard is the baseline and is not sent.
    public func sessionStarted(sessionID: UInt32) {
        queue.async { [self] in
            self.sessionID = sessionID
            sync.begin(changeCount: pasteboard.changeCount)
            timer?.cancel()
            let t = DispatchSource.makeTimerSource(queue: queue)
            t.schedule(deadline: .now() + Self.pollInterval, repeating: Self.pollInterval)
            t.setEventHandler { [weak self] in self?.poll() }
            t.resume()
            timer = t
        }
    }

    public func sessionEnded() {
        queue.async { [self] in
            timer?.cancel()
            timer = nil
            sessionID = nil
            sync.end()
        }
    }

    /// A message from the active session; anything but CLIPBOARD is ignored.
    public func deliver(_ message: Message) {
        guard case .clipboard(let clip) = message else { return }
        queue.async { [self] in
            guard let text = sync.receive(clip) else { return }
            sync.didWrite(changeCount: pasteboard.write(text))
            logger.log(.info, "clipboard", sessionID: sessionID ?? 0, generation: 0,
                       fields: "dir=in bytes=\(clip.data.count)")
        }
    }

    /// One poll step; internal so tests can drive it without the timer.
    func poll() {
        guard let sessionID else { return }
        let count = pasteboard.changeCount
        // Read the content only when something changed: cheap idle polls and no needless access to private content.
        guard sync.hasChanged(changeCount: count) else { return }
        switch sync.observe(changeCount: count, text: pasteboard.string, isConcealed: pasteboard.isConcealed) {
        case .nothing: break
        case .send(let clip):
            send(sessionID, .clipboard(clip))
            logger.log(.info, "clipboard", sessionID: sessionID, generation: 0, fields: "dir=out bytes=\(clip.data.count)")
        case .tooLarge(let bytes):
            logger.log(.info, "clipboard_too_large", sessionID: sessionID, generation: 0, fields: "bytes=\(bytes)")
        }
    }
}
