import CryptoKit

/// Pure clipboard-sharing decisions (docs/PROTOCOL.md 0x06). No pasteboard, no clock, no I/O; the host feeds it the
/// pasteboard's `changeCount` and text. Contents are private: nothing here logs, and only a SHA-256 digest of the last
/// received text is kept.
public struct ClipboardSync: Sendable {
    public enum Decision: Equatable, Sendable {
        case nothing
        case send(Clipboard)
        /// Text over the limit: not sent; the caller logs `clipboard_too_large bytes=` once.
        case tooLarge(bytes: Int)
    }

    public private(set) var enabled: Bool
    private var lastChangeCount: Int?
    /// changeCount our own write produced, plus the digest of the text we wrote.
    private var echoChangeCount: Int?
    private var echoDigest: SHA256.Digest?
    private var nextSeq: UInt32 = 0

    public init(enabled: Bool = true) { self.enabled = enabled }

    /// Session start (or the feature turned on): the current pasteboard becomes the baseline and is not sent.
    public mutating func begin(changeCount: Int) {
        lastChangeCount = changeCount
        echoChangeCount = nil
        echoDigest = nil
    }

    /// Session end: forget the baseline. Nothing is sent until `begin`.
    public mutating func end() {
        lastChangeCount = nil
        echoChangeCount = nil
        echoDigest = nil
    }

    public mutating func setEnabled(_ on: Bool, changeCount: Int) {
        guard on != enabled else { return }
        enabled = on
        if on, lastChangeCount != nil { begin(changeCount: changeCount) }
    }

    /// True when `observe` with this `changeCount` would look at the content (so idle polls can skip reading it).
    public func hasChanged(changeCount: Int) -> Bool {
        lastChangeCount != nil && changeCount != lastChangeCount
    }

    /// Called at every poll. `text` is the pasteboard string (nil when it has none); `isConcealed` marks
    /// `org.nspasteboard.ConcealedType` / `TransientType` / `AutoGeneratedType` content.
    public mutating func observe(changeCount: Int, text: String?, isConcealed: Bool) -> Decision {
        guard lastChangeCount != nil, changeCount != lastChangeCount else { return .nothing }
        lastChangeCount = changeCount
        guard enabled else { return .nothing }
        if changeCount == echoChangeCount { return .nothing }  // produced by our own write
        if isConcealed { return .nothing }
        guard let text, !text.isEmpty else { return .send(nextMessage { .empty(seq: $0) }) }
        if let echoDigest, Self.digest(text) == echoDigest { return .nothing }  // the text the tablet just sent
        let bytes = text.utf8.count
        guard bytes <= ProtocolConstants.clipboardMaxBytes else { return .tooLarge(bytes: bytes) }
        return .send(nextMessage { .text(seq: $0, text) })
    }

    /// An incoming CLIPBOARD. Returns the text to write to the pasteboard, or nil when it must be ignored
    /// (feature off, no session, EMPTY, unknown kind, invalid UTF-8, too long).
    public mutating func receive(_ message: Clipboard) -> String? {
        guard enabled, lastChangeCount != nil, message.data.count <= ProtocolConstants.clipboardMaxBytes,
              let text = message.validText else { return nil }
        echoDigest = Self.digest(text)
        return text
    }

    /// Call right after writing a received text, with the pasteboard's new `changeCount`.
    public mutating func didWrite(changeCount: Int) {
        echoChangeCount = changeCount
        lastChangeCount = changeCount
    }

    private mutating func nextMessage(_ make: (UInt32) -> Clipboard) -> Clipboard {
        defer { nextSeq &+= 1 }
        return make(nextSeq)
    }

    private static func digest(_ text: String) -> SHA256.Digest { SHA256.hash(data: Array(text.utf8)) }
}
