import Foundation
import YUV444Core
import YUV444GPU

/// Test clips for the Android decoder probe (T-254): the AVC444v2 pair of the scene, one HEVC Main stream per view
/// (`main_*.h265` = a plain 4:2:0 picture, `aux_*.h265` = the other chroma samples), Annex-B, `frames` pictures each,
/// a single IDR at frame 0 in both, plus reference PNGs and a metadata file.
func runClips(_ args: ProbeArgs) throws {
    let frames = args.int("frames", 600)
    let fps = args.int("fps", 60)
    let chroma = parseChromas(args.string("main-chroma", "box"))[0]
    let mainMbps = args.double("main-mbps", 40)
    let auxRatio = args.double("aux-ratio", 0.5)
    let out = dataDir(args)
    try FileManager.default.createDirectory(atPath: out, withIntermediateDirectories: true)
    let scene = Scene(frames: frames, grain: args.int("grain", 14))
    for size in parseSizes(args) {
        let rates = ClipNaming.bitrates(size: size, mainMbps: mainMbps, auxRatio: auxRatio)
        line("== clips \(size) frames=\(frames) fps=\(fps) main-chroma=\(chroma.rawValue) main=\(rates.mainKbps) kbps aux=\(rates.auxKbps) kbps")
        let r = try encodeSequence(scene: scene, size: size, frames: frames, fps: fps, chroma: chroma,
                                   mainKbps: rates.mainKbps, auxKbps: rates.auxKbps)
        line(String(format: "encoded in %.1f s (%.1f frames/s offline), hw=%@ settings main=%@ aux=%@ errors=%d",
                    r.seconds, Double(frames) / r.seconds, r.hardware, r.mainSettings, r.auxSettings, r.errors))
        var problems: [String] = []
        var meta: [String] = []
        for (name, view, outputs) in [(ClipNaming.mainName(size, fps: fps), "main", r.main),
                                      (ClipNaming.auxName(size, fps: fps), "aux", r.aux)] {
            var file = [UInt8]()
            var bytes = 0
            for o in outputs {
                guard let o, let annexB = VTStream.annexB(o.sample) else { problems.append("\(view): missing frame"); continue }
                file += annexB
                bytes += o.bytes
            }
            let path = (out as NSString).appendingPathComponent(name)
            try Data(file).write(to: URL(fileURLWithPath: path))
            let pictures = AnnexB.pictureCount(file), irap = AnnexB.irapCount(file)
            if pictures != frames { problems.append("\(view): pictures=\(pictures) != \(frames)") }
            if irap != 1 { problems.append("\(view): irap=\(irap) != 1") }
            let avgMbps = Double(bytes) * 8 / (Double(frames) / Double(fps)) / 1e6
            let phases = bytesByPhase(outputs, frames: frames)
            let phaseText = ScenePhase.allCases.map { String(format: "%@=%.1fkB", $0.rawValue, (phases.perPhase[$0] ?? 0) / 1000) }.joined(separator: " ")
            let text = String(format: "%@: %@ pictures=%d irap=%d bytes=%d avg=%.1f Mbps idr=%.0fkB per-frame[%@]",
                              view, name, pictures, irap, bytes, avgMbps, Double(phases.idr) / 1000, phaseText)
            line("  " + text)
            meta.append(text)
        }
        // Reference frames (source RGB) at the middle of each phase.
        var refs: [String] = []
        if !args.flag("no-png") {
            for phase in ScenePhase.allCases {
                let f = phase.start(frames: frames) + frames / 8
                let name = ClipNaming.referenceName(size, frame: f)
                try scene.writePNG(frame: f, size: size, to: URL(fileURLWithPath: (out as NSString).appendingPathComponent(name)))
                refs.append("\(name) (\(phase.rawValue))")
            }
        }
        let header = [
            "yuv444 test clips (T-255), generated by probes/yuv444-probe `yuv444-probe clips`",
            "layout: AVC444v2 (MS-RDPEGFX 3.3.8.3.3), two HEVC Main streams, one picture per frame in each, same frame index = same desktop frame",
            "size: \(size)  fps: \(fps)  frames: \(frames)  idr: frame 0 only in both streams  annexb: yes (VPS/SPS/PPS before the IDR)",
            "main view: Y444 + Cb/Cr 4:2:0 (\(chroma == .box ? "2x2 rounded mean = centred siting" : "even column/even row sample = top-left siting")); a decoder showing main only gets a normal 4:2:0 picture",
            "aux view: luma left half = Cb odd columns, right half = Cr odd columns; chroma planes = even columns of odd rows (x%4==0 -> Cb plane, x%4==2 -> Cr plane), left half Cb, right half Cr",
            "reconstruction: \(chroma == .box ? "even/even sample = main chroma as is, or 4*mean - other three (inverse box)" : "even/even sample = main chroma")",
            "colour: BT.709 full range, sRGB transfer (tags as MateBridge SDR session); the aux planes are DATA: sample them raw (no colour conversion)",
            "scene phases (frames): still 0-\(frames / 4 - 1), typing \(frames / 4)-\(frames / 2 - 1), scroll \(frames / 2)-\(3 * frames / 4 - 1), video \(3 * frames / 4)-\(frames - 1)",
            "bitrate: main \(rates.mainKbps) kbps, aux \(rates.auxKbps) kbps (average, fast profile, burst cap 2x)",
        ] + meta + ["references: " + refs.joined(separator: ", ")]
        try header.joined(separator: "\n").appending("\n")
            .write(toFile: (out as NSString).appendingPathComponent(ClipNaming.metaName(size, fps: fps)), atomically: true, encoding: .utf8)
        if problems.isEmpty { line("  OK: clips verified (\(frames) pictures each, one IDR)") }
        else { line("  PROBLEMS: " + problems.joined(separator: "; ")) }
    }
    line("clips in \(out)")
}

/// Writes one scene frame as PNG, to look at the content.
func runPreview(_ args: ProbeArgs) throws {
    let size = parseSizes(args, default: "2800x1840")[0]
    let frame = args.int("frame", 0)
    let frames = args.int("frames", 600)
    let path = (args.string("out", "~/.cache/matebridge-tools/data/yuv444/preview.png") as NSString).expandingTildeInPath
    try FileManager.default.createDirectory(atPath: (path as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
    try Scene(frames: frames).writePNG(frame: frame, size: size, to: URL(fileURLWithPath: path))
    line("wrote \(path)")
}
