// Reference generator for protocol/fixtures/crypto_vectors.json (PROTOCOL.md §9, decision 0010).
// Run: swift protocol/fixtures/crypto_vectors.swift > protocol/fixtures/crypto_vectors.json (after gen.py)
// Everything is derived from fixed inputs, so the output is deterministic. Both implementations must reproduce every
// value from the inputs listed under "inputs".
import CryptoKit
import Foundation

func hex(_ d: some DataProtocol) -> String { d.map { String(format: "%02x", $0) }.joined() }
func bytes(_ s: String) -> Data {
    var d = Data(); var i = s.startIndex
    while i < s.endIndex { let j = s.index(i, offsetBy: 2); d.append(UInt8(s[i..<j], radix: 16)!); i = j }
    return d
}
func le32(_ v: UInt32) -> Data { withUnsafeBytes(of: v.littleEndian) { Data($0) } }
func le64(_ v: UInt64) -> Data { withUnsafeBytes(of: v.littleEndian) { Data($0) } }

// Fixed inputs. Private keys are raw 32-byte P-256 scalars.
let clientPriv = try! P256.KeyAgreement.PrivateKey(rawRepresentation: bytes("c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c101"))
let hostPriv = try! P256.KeyAgreement.PrivateKey(rawRepresentation: bytes("a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a202"))
let clientPub = clientPriv.publicKey.x963Representation  // 65 bytes, 0x04 || X || Y
let hostPub = hostPriv.publicKey.x963Representation
let pairKey = bytes(String(repeating: "5a", count: 32))
let videoNonce = bytes("0f0e0d0c0b0a09080706050403020100")
// Transcript: the HELLO payload and the first HELLO_ACK payload exactly as on the wire (payload only, no frame header),
// read from the golden fixtures: hello.hex with hello_ack.hex (PAIRED) or hello_ack_pending.hex (PAIRING).
let fixtures = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
func fixturePayload(_ name: String) -> Data {
    let text = try! String(contentsOf: fixtures.appendingPathComponent(name + ".hex"), encoding: .utf8)
    let hexDigits = text.split(separator: "\n").map { line -> String in
        let code = line.split(separator: "#", maxSplits: 1, omittingEmptySubsequences: false).first ?? ""
        return code.filter { !$0.isWhitespace }
    }.joined()
    return bytes(hexDigits).dropFirst(5)  // 5-byte frame header
}
let helloPayload = fixturePayload("hello")
let ackPaired = fixturePayload("hello_ack")
let ackPairing = fixturePayload("hello_ack_pending")

let ecdh = try! clientPriv.sharedSecretFromKeyAgreement(with: hostPriv.publicKey).withUnsafeBytes { Data($0) }
func transcript(_ ack: Data) -> Data { Data(SHA256.hash(data: helloPayload + ack)) }

func expand(_ prk: Data, _ info: String, _ extra: Data = Data(), _ n: Int) -> Data {
    // HKDF-Expand (RFC 5869) with SHA-256.
    var out = Data(); var t = Data(); var i: UInt8 = 1
    while out.count < n {
        var h = HMAC<SHA256>(key: SymmetricKey(data: prk))
        h.update(data: t); h.update(data: Data(info.utf8) + extra); h.update(data: [i])
        t = Data(h.finalize()); out += t; i += 1
    }
    return out.prefix(n)
}
func extract(salt: Data, ikm: Data) -> Data {
    Data(HMAC<SHA256>.authenticationCode(for: ikm, using: SymmetricKey(data: salt)))
}

func schedule(paired: Bool) -> [String: String] {
    let ikm = (paired ? pairKey : Data()) + ecdh
    let salt = transcript(paired ? ackPaired : ackPairing)
    let prk = extract(salt: salt, ikm: ikm)
    var r: [String: String] = [
        "transcript_hash": hex(salt), "ikm": hex(ikm), "prk": hex(prk),
        "key_control_c2h": hex(expand(prk, "MB1 control c2h", Data(), 32)),
        "key_control_h2c": hex(expand(prk, "MB1 control h2c", Data(), 32)),
        "key_video_c2h": hex(expand(prk, "MB1 video c2h", videoNonce, 32)),
        "key_video_h2c": hex(expand(prk, "MB1 video h2c", videoNonce, 32)),
    ]
    if !paired {
        let sasBytes = expand(prk, "MB1 sas", Data(), 4)
        let sas = sasBytes.withUnsafeBytes { $0.loadUnaligned(as: UInt32.self).littleEndian } % 1_000_000
        r["sas_bytes"] = hex(sasBytes)
        r["sas"] = String(format: "%06u", sas)
        r["new_pair_key"] = hex(expand(prk, "MB1 pair", Data(), 32))
    }
    return r
}

func seal(key: String, counter: UInt64, type: UInt8, payload: Data) -> [String: String] {
    let plaintext = Data([type]) + payload
    let length = le32(UInt32(plaintext.count + 16))
    let nonce = Data(repeating: 0, count: 4) + le64(counter)
    let box = try! AES.GCM.seal(plaintext, using: SymmetricKey(data: bytes(key)),
                                nonce: AES.GCM.Nonce(data: nonce), authenticating: length)
    return ["key": key, "counter": String(counter), "type": String(format: "0x%02x", type), "payload": hex(payload),
            "nonce": hex(nonce), "frame": hex(length + box.ciphertext + box.tag)]
}

let paired = schedule(paired: true)
let pairing = schedule(paired: false)
let out: [String: Any] = [
    "comment": "PROTOCOL.md section 9. Generated by crypto_vectors.swift; do not edit by hand.",
    "inputs": [
        "client_eph_priv": hex(clientPriv.rawRepresentation), "client_eph_pub": hex(clientPub),
        "host_eph_priv": hex(hostPriv.rawRepresentation), "host_eph_pub": hex(hostPub),
        "pair_key": hex(pairKey), "video_nonce": hex(videoNonce),
        "hello_payload": hex(helloPayload), "hello_ack_paired_payload": hex(ackPaired),
        "hello_ack_pairing_payload": hex(ackPairing),
    ],
    "ecdh": hex(ecdh),
    "paired": paired,
    "pairing": pairing,
    "frames": [
        // PING (0x20) seq=7, sent_time_us=1127500000000, c2h counter 0 and 1 (same payload, different nonce).
        seal(key: paired["key_control_c2h"]!, counter: 0, type: 0x20, payload: le32(7) + le64(1_127_500_000_000)),
        seal(key: paired["key_control_c2h"]!, counter: 1, type: 0x20, payload: le32(7) + le64(1_127_500_000_000)),
        // RELEASE_ALL (0x16) reason=1, h2c direction key (a host never sends it; only the crypto is under test).
        seal(key: paired["key_control_h2c"]!, counter: 5, type: 0x16, payload: Data([1])),
        // Empty-payload frame, video h2c key.
        seal(key: paired["key_video_h2c"]!, counter: 0, type: 0x41, payload: Data()),
    ],
]
let json = try! JSONSerialization.data(withJSONObject: out, options: [.prettyPrinted, .sortedKeys])
print(String(data: json, encoding: .utf8)!)
