#!/usr/bin/env python3
"""Reference encoder for MateBridge protocol v0 golden vectors.

Regenerates protocol/fixtures/*.hex. The layouts here mirror docs/PROTOCOL.md exactly;
if they ever disagree, the document wins and this script is the bug.
Every fixture is a complete frame (5-byte header + payload), one field per line,
with the field name and value in a trailing comment. Tests strip comments and whitespace.

Usage: python3 protocol/fixtures/gen.py            # rewrite fixtures
       python3 protocol/fixtures/gen.py --check    # exit 1 if any fixture is stale
"""
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Message type codes (docs/PROTOCOL.md, "Mesaj tipleri").
T = {
    "HELLO": 0x01, "HELLO_ACK": 0x02, "STREAM_CONFIG": 0x03, "BYE": 0x04,
    "PEN": 0x10, "KEY": 0x11, "POINTER_REL": 0x12, "POINTER_ABS": 0x13,
    "SCROLL": 0x14, "PEN_GESTURE": 0x15, "RELEASE_ALL": 0x16,
    "PING": 0x20, "PONG": 0x21, "STATS": 0x22, "KEYFRAME_REQUEST": 0x23,
    "VIDEO_HELLO": 0x40, "VIDEO_FRAME": 0x41,
}

FMT = {"u8": "<B", "i8": "<b", "u16": "<H", "i16": "<h", "u32": "<I", "u64": "<Q", "f32": "<f"}


def field(kind, name, value, note=""):
    if kind == "bytes":
        data = bytes(value)
        shown = value.hex() if len(data) <= 16 else f"{len(data)} bytes"
    elif kind == "str8":
        raw = value.encode("utf-8")
        assert len(raw) <= 64, "str8 max 64 bytes"
        data = struct.pack("<B", len(raw)) + raw
        shown = repr(value)
    else:
        data = struct.pack(FMT[kind], value)
        shown = repr(value) if kind != "f32" else f"{value!r}"
    return data, f"{kind} {name} = {shown}" + (f" ({note})" if note else "")


def frame(msg, fields):
    payload = b"".join(d for d, _ in fields)
    lines = [
        (struct.pack("<B", T[msg]), f"header u8 type = 0x{T[msg]:02x} ({msg})"),
        (struct.pack("<I", len(payload)), f"header u32 length = {len(payload)}"),
    ] + fields
    return lines


def render(title, lines):
    out = [f"# {title}", "# generated by protocol/fixtures/gen.py; do not edit by hand"]
    width = max(len(d.hex(" ")) for d, _ in lines if len(d) <= 16)
    for data, comment in lines:
        if len(data) > 16:
            out.append(f"# {comment}")
            h = data.hex()
            out += [" ".join(h[i:i + 2] for i in range(j, min(j + 32, len(h)), 2)) for j in range(0, len(h), 32)]
        else:
            out.append(f"{data.hex(' '):<{width}}  # {comment}")
    return "\n".join(out) + "\n"


def pen_sample(dt_us, x, y, p, tx, ty, flags, note):
    parts = [
        field("u32", "dt_us", dt_us), field("u16", "x", x), field("u16", "y", y),
        field("u16", "pressure", p), field("i16", "tilt_x", tx), field("i16", "tilt_y", ty),
        field("u8", "flags", flags, note), field("u8", "reserved", 0),
    ]
    return [(d, f"  {c}") for d, c in parts]


DEVICE_ID = bytes.fromhex("0123456789abcdef0123456789abcdef")

FIXTURES = {
    "hello": ("HELLO: tablet introduces itself", frame("HELLO", [
        field("u16", "protocol_version", 0),
        field("bytes", "device_id", DEVICE_ID, "random per install"),
        field("u16", "screen_width_px", 2800),
        field("u16", "screen_height_px", 1840),
        field("u16", "density_dpi", 360),
        field("u16", "max_refresh_hz", 144),
        field("u32", "capabilities", 0x000000FF, "PEN|PEN_HOVER|PEN_TILT|KEYBOARD|TOUCHPAD|TOUCH|H264|HEVC"),
        field("str8", "device_name", "MatePad Pro"),
    ])),
    "hello_ack": ("HELLO_ACK: accepted", frame("HELLO_ACK", [
        field("u16", "protocol_version", 0),
        field("u8", "status", 0, "ACCEPTED"),
        field("u8", "reserved", 0),
        field("u32", "session_id", 0xA1B2C3D4),
        field("u16", "video_port", 47001),
        field("str8", "host_name", "Mac mini"),
    ])),
    "hello_ack_pending": ("HELLO_ACK: waiting for approval on the Mac", frame("HELLO_ACK", [
        field("u16", "protocol_version", 0),
        field("u8", "status", 1, "PENDING_APPROVAL"),
        field("u8", "reserved", 0),
        field("u32", "session_id", 0),
        field("u16", "video_port", 0),
        field("str8", "host_name", "Mac mini"),
    ])),
    "stream_config": ("STREAM_CONFIG: HEVC 2800x1840@60, sRGB full range", frame("STREAM_CONFIG", [
        field("u8", "codec", 2, "HEVC"),
        field("u8", "reserved", 0),
        field("u16", "width_px", 2800),
        field("u16", "height_px", 1840),
        field("u16", "fps", 60),
        field("u32", "bitrate_kbps", 50000),
        field("u8", "color_primaries", 1, "BT.709"),
        field("u8", "transfer", 13, "sRGB / IEC 61966-2-1"),
        field("u8", "matrix", 1, "BT.709"),
        field("u8", "full_range", 1),
    ])),
    "bye": ("BYE: normal shutdown", frame("BYE", [
        field("u8", "reason", 0, "NORMAL"),
    ])),
    "pen_hover_to_contact": ("PEN: hover enter, touch down, stroke, lift", frame("PEN", [
        field("u8", "tool", 0, "PEN"),
        field("u8", "count", 4),
        field("u16", "reserved", 0),
        field("u64", "base_time_us", 1127411618000),
    ] + pen_sample(0, 22364, 12738, 0, 3000, 2500, 0x02, "IN_RANGE")
      + pen_sample(3000, 22380, 12750, 288, 3000, 2500, 0x03, "IN_RANGE|CONTACT")
      + pen_sample(6000, 22410, 12771, 32768, 2980, 2490, 0x03, "IN_RANGE|CONTACT")
      + pen_sample(9000, 22430, 12790, 0, 2980, 2490, 0x02, "IN_RANGE, contact lifted"))),
    "pen_leave": ("PEN: out of range (proximity leave)", frame("PEN", [
        field("u8", "tool", 0, "PEN"),
        field("u8", "count", 1),
        field("u16", "reserved", 0),
        field("u64", "base_time_us", 1127411700000),
    ] + pen_sample(0, 22430, 12790, 0, 0, 0, 0x00, "not in range"))),
    "pen_eraser": ("PEN: eraser tool in contact with barrel button", frame("PEN", [
        field("u8", "tool", 1, "ERASER"),
        field("u8", "count", 1),
        field("u16", "reserved", 0),
        field("u64", "base_time_us", 1127411800000),
    ] + pen_sample(0, 1000, 2000, 65535, -32767, 0, 0x07, "IN_RANGE|CONTACT|BUTTON"))),
    "key_down": ("KEY: A down, Num Lock on", frame("KEY", [
        field("u64", "time_us", 1127463498000),
        field("u16", "scan_code", 30, "evdev KEY_A"),
        field("u16", "android_key_code", 29, "KEYCODE_A"),
        field("u8", "action", 1, "DOWN"),
        field("u8", "lock_state", 0x02, "NUM_LOCK"),
        field("u16", "reserved", 0),
    ])),
    "key_up_caps": ("KEY: Caps Lock up, Caps and Num Lock on", frame("KEY", [
        field("u64", "time_us", 1127463600000),
        field("u16", "scan_code", 58, "evdev KEY_CAPSLOCK"),
        field("u16", "android_key_code", 115, "KEYCODE_CAPS_LOCK"),
        field("u8", "action", 0, "UP"),
        field("u8", "lock_state", 0x03, "CAPS_LOCK|NUM_LOCK"),
        field("u16", "reserved", 0),
    ])),
    "pen_gesture": ("PEN_GESTURE: M-Pencil double tap", frame("PEN_GESTURE", [
        field("u64", "time_us", 1127465515000),
        field("u8", "gesture", 1, "DOUBLE_TAP"),
        field("u8", "reserved", 0),
        field("u16", "reserved2", 0),
    ])),
    "pointer_rel": ("POINTER_REL: move with left button held", frame("POINTER_REL", [
        field("u64", "time_us", 1127500489000),
        field("f32", "dx", 2.5),
        field("f32", "dy", -1.25),
        field("u8", "buttons", 0x01, "LEFT"),
        field("u8", "reserved", 0),
        field("u16", "reserved2", 0),
    ])),
    "pointer_abs": ("POINTER_ABS: finger touch pressed at screen center", frame("POINTER_ABS", [
        field("u64", "time_us", 1127500500000),
        field("u16", "x", 32768),
        field("u16", "y", 32768),
        field("u8", "buttons", 0x01, "LEFT"),
        field("u8", "source", 0, "TOUCH"),
        field("u16", "reserved", 0),
    ])),
    "scroll": ("SCROLL: two-finger scroll, changed phase", frame("SCROLL", [
        field("u64", "time_us", 1127500600000),
        field("f32", "dx", 0.0),
        field("f32", "dy", 12.5),
        field("u8", "phase", 2, "CHANGED"),
        field("u8", "momentum_phase", 0, "NONE"),
        field("u16", "reserved", 0),
    ])),
    "release_all": ("RELEASE_ALL: app went to background", frame("RELEASE_ALL", [
        field("u8", "reason", 1, "BACKGROUND"),
    ])),
    "ping": ("PING", frame("PING", [
        field("u32", "seq", 7),
        field("u64", "sender_time_us", 1127500700000),
    ])),
    "pong": ("PONG", frame("PONG", [
        field("u32", "seq", 7),
        field("u64", "echo_time_us", 1127500700000),
        field("u64", "responder_time_us", 98765432100),
    ])),
    "stats": ("STATS: one-second window", frame("STATS", [
        field("u32", "interval_ms", 1000),
        field("u32", "frames_received", 60),
        field("u32", "frames_decoded", 60),
        field("u32", "frames_rendered", 59),
        field("u32", "frames_dropped", 1),
        field("u32", "decode_time_avg_us", 4200),
        field("u32", "latency_avg_us", 23000),
        field("u32", "bytes_received", 6250000),
    ])),
    "keyframe_request": ("KEYFRAME_REQUEST: decoder lost reference", frame("KEYFRAME_REQUEST", [
        field("u8", "reason", 1, "DECODE_ERROR"),
    ])),
    "video_hello": ("VIDEO_HELLO: first message on the video connection", frame("VIDEO_HELLO", [
        field("u16", "protocol_version", 0),
        field("u16", "reserved", 0),
        field("u32", "session_id", 0xA1B2C3D4),
    ])),
    "video_frame": ("VIDEO_FRAME: HEVC keyframe, single fragment (payload shortened)", frame("VIDEO_FRAME", [
        field("u32", "frame_seq", 1),
        field("u64", "capture_time_us", 98765000000),
        field("u8", "flags", 0x01, "KEYFRAME"),
        field("u8", "codec", 2, "HEVC"),
        field("u16", "fragment_index", 0),
        field("u16", "fragment_count", 1),
        field("u16", "reserved", 0),
        field("u32", "frame_size", 8),
        field("bytes", "data", bytes.fromhex("0000000126010af0"), "Annex-B, IDR NAL start"),
    ])),
    "video_frame_config": ("VIDEO_FRAME: codec configuration only (HEVC VPS start, shortened)", frame("VIDEO_FRAME", [
        field("u32", "frame_seq", 0),
        field("u64", "capture_time_us", 98764990000),
        field("u8", "flags", 0x02, "CODEC_CONFIG"),
        field("u8", "codec", 2, "HEVC"),
        field("u16", "fragment_index", 0),
        field("u16", "fragment_count", 1),
        field("u16", "reserved", 0),
        field("u32", "frame_size", 6),
        field("bytes", "data", bytes.fromhex("000000014001"), "Annex-B, VPS NAL start"),
    ])),
}


def main():
    check = "--check" in sys.argv
    stale = []
    for name, (title, lines) in FIXTURES.items():
        text = render(title, lines)
        path = HERE / f"{name}.hex"
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
    extra = sorted(p.stem for p in HERE.glob("*.hex") if p.stem not in FIXTURES)
    if check and (stale or extra):
        print("stale fixtures:", stale, "unknown fixtures:", extra)
        sys.exit(1)
    if not check:
        print(f"wrote {len(FIXTURES)} fixtures" + (f"; unknown files present: {extra}" if extra else ""))


if __name__ == "__main__":
    main()
